---

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install Apache Web server
      yum:
        name: httpd
        state: present

    - name: Install Tom cat Application server
      yum:
        name: tomcat
        state: present

    - name: start Tom cat Application server
      service:
        name: tomcat
        state: started
        enabled: yes

    - name: start Apache web server
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install MySQL repository
      yum:
        name: "https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm"
        state: present

    - name: Install MySQL database
      yum:
        name: mysql-community-server
        state:  present

    - name: Start Mysql Service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install Telnet
      yum:
        name: telnet
        state: present

    - name: Install Curl
      yum:
        name: curl
        state: present

    - name: Install Nslookup
      yum:
        name: bind-utils
        state: present
