---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: modify ec2 group
      ec2_group:
#  Provide your Security group name to update
        name: sg_devops
        description: EC2 group port open
#   Provide Your vpc-id
        vpc_id: vpc-0ff77add466e6e7eb
        region: us-east-1
        rules:
          - proto: tcp
            ports:
              - 80
              - 3306
              - 22
              - 8080
            cidr_ip: 0.0.0.0/0
          

